<a href="https://colab.research.google.com/github/ConstantInKazancev/Test/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# a)
import numpy as np

# b)
 
x = np.zeros(10, dtype = 'int16')
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
# c)

a = np.ones(10, dtype = 'int16')
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
# d)

a = np.full((10), 5, dtype = 'int16')
print(a)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# e)

e = np.arange(10, 51, dtype = 'int16')
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# f)

e = np.arange(10, 51, 2, dtype = 'int16')
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# g)

e = np.random.randint(0, 9, size=(3, 3))
print(e)

[[2 3 8]
 [3 7 6]
 [3 6 4]]


In [ ]:
# h)

i = np.identity(3, dtype = 'int16')
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# i)

i = np.random.rand()
print(i)

0.01944751277110912


In [ ]:
# j)

i= np.random.normal(size = 25)
print(i)

[-2.26815312  0.04515069 -0.45694704 -1.24563815  1.05345812  0.57320165
 -1.97104496 -0.08363274  0.7179526  -1.54796812  1.78432972 -1.76376378
  0.06669329  1.05201523 -0.33901458 -0.71328652 -0.09952985  0.26741573
  0.1034243   0.84704127 -1.70239264 -0.98794225  0.40437732 -1.19845711
  0.36495067]


In [ ]:
# k)

k = np.linspace(0.01, 1, 100).reshape(10, 10)
print(k)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# l)

mat = np.arange(1,26).reshape(5,5)

mat[2:5, 1:5]




array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# m) 

print(mat[3, -1])

20
--------


In [ ]:
# n)

mat[0:3, 1].reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# o)

mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# p)

print(mat[3:])
# можно ещё так
print(mat[-2:])

[[16 17 18 19 20]
 [21 22 23 24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# q)

print(np.sum(mat))

325


In [ ]:
# r)

np.std(mat)

7.211102550927978

In [ ]:
# s)

print(sum(mat))

[55 60 65 70 75]
